version: "3"
services:
  postgres:
    image: "postgres:15-alpine"
    container_name: more-nearby-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:?}
      - PGDATA=${PGDATA:?}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - network

  mongo:
    image: mongo
    container_name: more-nearby-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
    networks:
      - network

  server:
    build:
      context: .
      dockerfile: ./main-backend/Dockerfile
    restart: unless-stopped
    container_name: more-nearby-main-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - network

  frontend:
    build:
      context: .
      dockerfile: ./web/DockerFile
    restart: unless-stopped
    container_name: more-nearby-web
    ports:
      - "3000:3000"
    network:
      - network

  emulator:
    build:
      context: .
      dockerfile: ./emulator/Dockerfile
    restart: unless-stopped
    container_name: more-nearby-emulator
    depends_on:
      - mongo
    network:
      - network

networks:
  network:
    driver: bridge
