version: '3'
services:
  postgres:
    image: "postgres:15-alpine"
    container_name: more-nearby-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:?}
      - PGDATA=${PGDATA:?}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - network

  mongo:
    image: mongo
    container_name: more-nearby-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - './data/mongo:/data/db'
    networks:
      - network

networks:
  network:
    driver: bridge